import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useState, useEffect } from "react";
import axios from "axios";
import { useReducer } from "next/router";
const inter = Inter({ subsets: ["latin"] });

const apiKey = "7ce54c3a3fa8432ab3e104604231110";
export default function Home() {
  const [weatherData, setWeatherData] = useState(null);
  const [location, setLocation] = useState("");

  const getWeatherData = async () => {
    const apiUrl = `http://api.weatherapi.com/v1/current.json?key=${apiKey}&q=${location}&aqi=yes`;
    console.log(apiUrl);
    const response = await axios.get(apiUrl);
    console.log("response", response);
    setWeatherData(response.data);
  };

  const handleInputChange = (e) => {
    setLocation(e.target.value);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <input
            type={"text"}
            value={location}
            className="input_bar"
            placeholder="Enter the location"
            onChange={handleInputChange}
          />
          <button
            className="btn"
            onClick={() => {
              getWeatherData();
            }}
          >
            Check weather{" "}
          </button>
          {weatherData && (
            <div>
              <h1>Location: {weatherData?.location?.name}</h1>
            </div>
          )}
          {weatherData && (
            <div>
              <h1>Temperature: {weatherData?.current?.temp_c}</h1>
            </div>
          )}
          {weatherData && <h1> Sky: {weatherData?.current?.condition.text}</h1>}
          {weatherData && <h1> Humidity: {weatherData?.current?.humidity}</h1>}
          {weatherData && (
            <h1> Wind Degree: {weatherData?.current?.wind_degree}</h1>
          )}
          {weatherData && (
            <h1> Wind Direction: {weatherData?.current?.wind_dir}</h1>
          )}
          {console.log("=============", weatherData)}
        </div>
      </main>
    </>
  );
}
